### PR TITLE
Fall back to running man without -W

### LINKED ISSUE #12: Showing man page fails when info not found
The call to the man program has man -W and there is no option for man -W causing an error.

In manual.c at line 185 looks like the problem:

`	snprintf(buf, sizeof(buf), "man -w -W %s %s", ManOptions, name);`

Maybe -C for configuration. This is a problem when the info page is not found.

### PR DESCRIPTION
**Pull request by whitelynx**
…since some implementations don't allow that.

Fixes #12.

Change courtesy of [loreb](https://github.com/loreb): https://github.com/baszoetekouw/pinfo/issues/12#issuecomment-884322986

### CODE REVIEW

File: src/manual.c [hunk 1]
```diff
@@ -186,8 +186,14 @@ set_initial_history(char *name)
 		pathFile = popen(buf, "r");
 		if (fgets(buf, sizeof(buf), pathFile)==NULL)
 		{
-			fprintf(stderr, "Error executing command '%s'\n", buf);
-			exit(1);
+			/* Try without -W */
```
Comment (xaizek) [inline src/manual.c:189]: This lacks `pclose(pathFile);` to not leak that `FILE`.

Comment (whitelynx) [reply src/manual.c:190]: Added.

**Review by baszoetekouw — APPROVED** [review]

**Comment by baszoetekouw** [comment]
Thanks you, merging!
